version: '3.3'

services:
  redis:
    image: redis

  worker:
    image: dramatiq_cached_results
    command: dramatiq app
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  app:
    image: dramatiq_cached_results
    build: .
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - worker
