version: '3.3'

services:
  redis:
    image: redis

  worker:
    image: dramatiq_cached_results
    build: .
    command: dramatiq actors
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
